export const TIMING = {
  LOOP_PREPARATION_MS: 3000,
  VIDEO_SYNC_TOLERANCE_S: 0.3,
  OPTIMISTIC_DELETE_DELAY_MS: 260,
  NETWORK_TIMEOUT_MS: 45000,
  RECORDING_TOLERANCE_S: 0.15,
  TAKES_REFETCH_INTERVAL_MS: 20000,
  CONTROLS_HIDE_DELAY_MS: 3000,
  SESSION_ACCESS_CHECK_INTERVAL_MS: 30000,
  COUNTDOWN_BEEP_INTERVAL_MS: 1000,
  TEXT_LIVE_CHANGE_DEBOUNCE_MS: 500,
  AUDIO_PROBE_TIMEOUT_MS: 12000,
  LOOP_SILENCE_DELAY_MS: 3000,
  WS_RECONNECT_BASE_DELAY_MS: 1000,
  WS_RECONNECT_MAX_DELAY_MS: 30000,
} as const;

export const VALIDATION = {
  MICROPHONE_DURATION_MS: 500,
  AUDIO_LEVEL_MIN_THRESHOLD: 0.01,
} as const;

export const THRESHOLDS = {
  QUALITY_MIN_SCORE: 0.6,
  AUDIO_MIN_DURATION_S: 0.5,
  AUDIO_MIN_SAMPLES: 100,
  VIDEO_PREROLL_S: 3,
} as const;
